# Generated by Django 6.0.3 on 2026-03-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_order_status_favorite_message"),
    ]

    operations = []
