# Generated by Django 6.0.3 on 2026-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_auto_20260312_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_refund",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "未支付"),
                    ("paid", "已支付"),
                    ("not_shipped", "未发货"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("refund", "退款中"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
