# Generated by Django 6.0.3 on 2026-03-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_order_is_paid_order_is_received_order_is_refund_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("detail", models.CharField(max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
