# Generated by Django 6.0.3 on 2026-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_post_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("literature", "文学艺术"),
                    ("technology", "科技"),
                    ("education", "教材"),
                    ("exam", "考试"),
                    ("life", "生活"),
                    ("economics", "经济管理"),
                ],
                default="literature",
                max_length=50,
            ),
        ),
    ]
