# Generated by Django 6.0.3 on 2026-03-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
