# Generated by Django 6.0.3 on 2026-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "未支付"),
                    ("paid", "已支付"),
                    ("not_shipped", "未发货"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("refund", "退款中"),
                    ("cancelled", "已取消"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
