# Generated by Django 6.0.3 on 2026-05-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("literature", "文学艺术"),
                    ("technology", "科技"),
                    ("education", "教材"),
                    ("life", "生活"),
                    ("economics", "经济管理"),
                    ("history", "历史文化"),
                    ("psychology", "心理学"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
